bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    
    use_feedback: true
    
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    odom_topic: /odom
    use_sim_time: True
    controller_frequency: 5.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: teb_local_planner::TebLocalPlannerROS

      teb_autosize: 1.0
      dt_ref: 0.3
      dt_hysteresis: 0.1 
      max_samples: 500
      global_plan_overwrite_orientation: False
      allow_init_with_backwards_motion: False
      max_global_plan_lookahead_dist: 3.0
      global_plan_viapoint_sep: 0.3
      global_plan_prune_distance: 1.0
      exact_arc_length: False
      feasibility_check_no_poses: 2
      publish_feedback: False
          
      # Robot
              
      max_vel_x: 0.26
      max_vel_theta: 1.0 
      acc_lim_x: 2.5
      acc_lim_theta: 3.2

      footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "line"
        line_start: [0.0, 0.0] # for type "line"
        line_end: [-0.1275, 0.0] # for type "line"
      # GoalTolerance
              
      free_goal_vel: False
          
      # Obstacles
          
      min_obstacle_dist: 0.27
      inflation_dist: 0.6
      include_costmap_obstacles: True
      costmap_obstacles_behind_robot_dist: 1.0
      obstacle_poses_affected: 15

      dynamic_obstacle_inflation_dist: 0.6
      include_dynamic_obstacles: True 

      costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
      costmap_converter_spin_thread: True
      costmap_converter_rate: 5

      # Optimization
          
      no_inner_iterations: 5
      no_outer_iterations: 4
      optimization_activate: True
      optimization_verbose: False
      penalty_epsilon: 0.1
      obstacle_cost_exponent: 4.0
      weight_max_vel_x: 0.5
      weight_max_vel_theta: 0.5
      weight_acc_lim_x: 0.5
      weight_acc_lim_theta: 10.5
      weight_kinematics_nh: 1000.0
      weight_kinematics_forward_drive: 3.0
      weight_kinematics_turning_radius: 1.0
      weight_optimaltime: 1.0 # must be > 0
      weight_shortest_path: 0.0
      weight_obstacle: 100.0
      weight_inflation: 0.2
      weight_dynamic_obstacle: 10.0 # not in use yet
      weight_dynamic_obstacle_inflation: 0.2
      weight_viapoint: 50.0
      weight_adapt_factor: 2.0

      # Homotopy Class Planner

      enable_homotopy_class_planning: True
      enable_multithreading: True
      max_number_classes: 4
      selection_cost_hysteresis: 5.0
      selection_prefer_initial_plan: 1.0
      selection_obst_cost_scale: 1.0
      selection_alternative_time_cost: True

      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5.0
      roadmap_graph_area_length_scale: 1.0
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_heading_threshold: 0.45
      switching_blocking_period: 0.0
      viapoints_all_candidates: True
      delete_detours_backwards: True
      max_ratio_detours_duration_best_duration: 3.0
      visualize_hc_graph: False
      visualize_with_time_as_z_axis_scale: 0.0

      # Recovery
      
      shrink_horizon_backup: True
      shrink_horizon_min_duration: 10.0
      oscillation_recovery: True
      oscillation_v_eps: 0.1
      oscillation_omega_eps: 0.1
      oscillation_recovery_min_duration: 10.0
      oscillation_filter_duration: 10.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0 #10.0
      publish_frequency: 15.0 #10.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 10 #8
      height: 10 #8
      resolution: 0.05
      footprint: "[[0.1675,0.215], [-0.318,0.215], [-0.318,-0.215], [0.1675,-0.215]]"
      plugins: ["obstacle_layer", "stvl_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 2.58 #1.0
        cost_scaling_factor: 1.75 #3.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan virtual_obstacle_source scan2
        scan:
          topic: /scan_filtered #/scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 8.0
          raytrace_max_range: 9.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: False
        scan2:
          topic: /scan2
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.0
          raytrace_max_range: 3.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: False
        virtual_obstacle_source:
          topic: /Local_virtual_wall
          data_type: PointCloud2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 100.0
          raytrace_max_range: 101.0
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 1.0 #2.0
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: true
        unknown_threshold: 15.0
        mark_threshold: 2
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true #false
        transform_tolerance: 0.1 #0.2 #1.0
        mapping_mode: false
        map_save_duration: 60.0
        observation_sources: realsense_cloud livox_cloud
        realsense_cloud:
          data_type: "PointCloud2"
          topic: /camera1/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 2.0
          min_obstacle_height: 0.1 #0.05
          max_obstacle_height: 2.0
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          filter: "voxel" #"passthrough"
          voxel_min_points: 0
          clear_after_reading: true
          max_z: 2.0 # 0.7
          min_z: 0.1
          vertical_fov_angle: 1.01229 #0.7
          horizontal_fov_angle: 1.51844 #1.20428
          decay_acceleration: 2.0 #1.0
          model_type: 0
        livox_cloud:
          data_type: "PointCloud2"
          topic: /livox/lidar
          marking: true
          clearing: true
          obstacle_range: 8.0
          min_obstacle_height: 0.05
          max_obstacle_height: 2.0
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          filter: "voxel" #"passthrough"
          voxel_min_points: 0
          clear_after_reading: true
          max_z: 2.0 # 0.7
          min_z: 0.1
          vertical_fov_angle: 0.907571 #52deg
          horizontal_fov_angle: 6.28319 #360deg
          decay_acceleration: 0.0 #1.0
          model_type: 0
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      transform_tolerance: 0.5
      update_frequency: 5.0 #10.0
      publish_frequency: 5.0 #10.0
      width: 15
      height: 15
      global_frame: map
      robot_base_frame: base_footprint
      footprint: "[[0.1675,0.215], [-0.318,0.215], [-0.318,-0.215], [0.1675,-0.215]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: virtual_obstacle_source scan
        scan:
          topic: /scan_filtered #/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 9.0
          raytrace_min_range: 0.0
          obstacle_max_range: 8.0
          obstacle_min_range: 0.0
        virtual_obstacle_source:
          topic: /Global_virtual_wall
          data_type: PointCloud2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 100.0
          raytrace_max_range: 101.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.7
      always_send_full_costmap: True

map_server:
  ros__parameters:
    yaml_filename: "" #"office.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 15.0 #20.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint #base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [2.0, 0.0, 2.0]
    min_velocity: [-2.0, 0.0, -2.0]
    max_accel: [3.5, 0.0, 3.5]
    max_decel: [-3.5, 0.0, -3.5]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel_nav2"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0

    polygons: ["VelocityPolygonStop"]
    VelocityPolygonStop:
      type: "velocity_polygon"
      action_type: "slowdown" #"stop"
      min_points: 6
      visualize: True
      enabled: True
      polygon_pub_topic: "velocity_polygon_slow"
      velocity_polygons: ["translation_forward_high", "translation_forward_low", "translation_backward", "stopped"]
      holonomic: false
      translation_forward_high:
        points: "[[1.1675, 0.315], [1.1675, -0.315], [-0.32, -0.315], [-0.32, 0.315]]"
        linear_min: 0.7
        linear_max: 1.5
        theta_min: -1.5
        theta_max: 1.5
      translation_forward_low:
        points: "[[0.5, 0.315], [0.5, -0.315], [-0.32, -0.315], [-0.32, 0.315]]"
        linear_min: 0.3
        linear_max: 0.699
        theta_min: -1.5
        theta_max: 1.5
      translation_backward:
        points: "[[0.2, 0.315], [0.2, -0.315], [-0.6, -0.315], [-0.6, 0.315]]"
        linear_min: -1.0
        linear_max: -0.05
        theta_min: -1.5
        theta_max: 1.5
      stopped:
        points: "[[0.2, 0.25], [0.2, -0.25], [-0.35, -0.25], [-0.35,  0.25]]"
        linear_min: 0.0
        linear_max: 0.0
        theta_min: -1.5
        theta_max: 1.5
    observation_sources: ["scan", "scan2"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True
    scan2:
      type: "scan"
      topic: "scan2"
      min_height: 0.15
      max_height: 2.0
      enabled: True

